import {AutoTokenizer} from '@huggingface/transformers';
import {manifest,normal,ort,rgbaFromNchw,session} from './common';
import {AdaptiveMemoryBank,concatMemory} from './memory-bank';
export class MemFlowRuntime{private m!:Awaited<ReturnType<typeof manifest>>;private text!:ort.InferenceSession;private generator!:ort.InferenceSession;private vae!:ort.InferenceSession;private tokenizer:any;private bank!:AdaptiveMemoryBank;
 async load(url:string,p:(s:string)=>void){this.m=await manifest(url);const cfg=this.m.memory??{capacity:16,topK:4,keySize:4096};this.bank=new AdaptiveMemoryBank(cfg.capacity,cfg.topK);p('Loading MemFlow components…');this.tokenizer=await AutoTokenizer.from_pretrained(this.m.models.tokenizer);[this.text,this.generator,this.vae]=await Promise.all([session(this.m.models.text_encoder),session(this.m.models.generator),session(this.m.models.vae_decoder)]);p(`MemFlow ready — memory 0/${cfg.capacity}`)}
 private async condition(prompt:string){const tok=await this.tokenizer(prompt,{padding:'max_length',max_length:512,truncation:true});const ids=BigInt64Array.from(Array.from(tok.input_ids.data as ArrayLike<number>),BigInt);const out=await this.text.run({input_ids:new ort.Tensor('int64',ids,[1,ids.length])});return out.last_hidden_state??Object.values(out)[0]}
 private query(embedding:ort.Tensor){const x=embedding.data as Float32Array,d=embedding.dims.at(-1)??x.length,q=new Float32Array(d),tokens=x.length/d;for(let t=0;t<tokens;t++)for(let i=0;i<d;i++)q[i]+=x[t*d+i]/tokens;return q}
 async run(prompt:string,chunks:number,seed:number,onFrame:(x:{rgba:Uint8ClampedArray,width:number,height:number})=>void,signal:AbortSignal){const cond=await this.condition(prompt),query=this.query(cond),w=this.m.width/8,h=this.m.height/8;
  for(let c=0;c<chunks;c++){if(signal.aborted)throw new DOMException('Stopped','AbortError');const selected=this.bank.retrieve(query),memory=concatMemory(selected.map(x=>x.entry.value));const feeds:Record<string,ort.Tensor>={noise:new ort.Tensor('float32',normal(4*w*h,seed+c),[1,4,1,h,w]),prompt_embeds:cond,chunk_index:new ort.Tensor('int64',BigInt64Array.of(BigInt(c)),[1])};if(memory)feeds.memory_values=memory;feeds.memory_mask=new ort.Tensor('int64',BigInt64Array.of(BigInt(memory?.dims[1]??0)),[1]);const out=await this.generator.run(feeds);const latent=out.latents??out.sample??Object.values(out)[0],key=out.memory_key,value=out.memory_value;if(key&&value)this.bank.add(Float32Array.from(key.data as ArrayLike<number>),value);const decoded=await this.vae.run({latent_sample:latent});const rgb=(decoded.sample??Object.values(decoded)[0]).data as Float32Array;onFrame({rgba:rgbaFromNchw(rgb,this.m.width,this.m.height),width:this.m.width,height:this.m.height});}}
}
